PORT: ${PORT:-4000}
POSTGRES_DB_HOST: ${POSTGRES_DB_HOST}
POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
POSTGRES_DB_USER: ${POSTGRES_DB_USER}
POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
POSTGRES_DB_NAME: ${POSTGRES_USER}